name: Publish Helm Chart

on:
  push:
    tags:
      - "v*" # Trigger only when pushing tags starting with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Charts
        run: |
          mkdir -p .cr-release-packages
          helm package . --destination .cr-release-packages --version ${GITHUB_REF#refs/tags/v}

      - name: Create gh-pages branch if not exists
        run: |
          if ! git ls-remote --heads origin gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
            git commit --allow-empty -m "Create gh-pages branch"
            git push origin gh-pages
          fi

      - name: Clean and switch to gh-pages branch
        run: |
          # Save packaged files
          mv .cr-release-packages /tmp/
          # Clean working directory
          git clean -fdx
          # Switch to gh-pages branch
          git checkout gh-pages
          git pull origin gh-pages
          # Restore packaged files
          mv /tmp/.cr-release-packages .

      - name: Update Helm repository
        run: |
          # Copy packaged charts to root directory
          cp .cr-release-packages/* .
          # Update or create index.yaml
          if [ -f index.yaml ]; then
            helm repo index . --url https://${{ github.repository_owner }}.github.io/$(basename ${{ github.repository }}) --merge index.yaml
          else
            helm repo index . --url https://${{ github.repository_owner }}.github.io/$(basename ${{ github.repository }})
          fi
          # Commit changes
          git add .
          git commit -m "Release chart version ${GITHUB_REF#refs/tags/v}" || echo "No changes to commit"
          git push origin gh-pages
